services:
  recommendation:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - mock-model
    volumes:
      - ./offline.db:/app/offline.db
  redis:
    image: redis:7-alpine
    ports:
      - "16379:6379"
  mock-model:
    image: python:3.11-slim
    volumes:
      - ./scripts:/srv/scripts
    working_dir: /srv/scripts
    command: ["python", "-u", "mock_model_service.py"]
    ports:
      - "5001:5001"
